### ISSUE TITLE
fetchDeferredAppLink doesn't work on IOS 15,14

### ISSUE THREAD

**Issue by tranducduong1994** [thebergamo/react-native-fbsdk-next#104]
## 🐛 Bug Report

This is my code:
  
```javascript
const getDeferredAppLinkData = async () => {
      try {
       const resultTrackingStatus = await requestTrackingPermission();
        if (
          resultTrackingStatus === 'authorized' 
        ) {
          return;
        }
        await Settings.initializeSDK();
        await Settings.setAdvertiserTrackingEnabled(true);
        let deferredAppLinkData = await AppLink.fetchDeferredAppLink();
        console.log('From fb', deferredAppLinkData); // =====> ALWAYS undefined
        if (deferredAppLinkData) AsyncStorage.setItem('deferredAppLinkData', deferredAppLinkData);
      } catch (error) {}
    };
    getDeferredAppLinkData();
```

AppLink.fetchDeferredAppLink(); always return undefined in IOS platform. it worked in android platform as well.

## To Reproduce

I used https://developers.facebook.com/tools/app-ads-helper/ to send a test deep-link to my app after installing the app.

## Expected Behavior

AppLink.fetchDeferredAppLink must return deep-link from https://developers.facebook.com/tools/app-ads-helper/ after installing the app.

## Environment
IOS: 14 or 15

**Comment by mikehardy** [comment]
Hi there! Just to set expectations, I don't see a lot of people helping to troubleshoot issues in this repo, so you should have the expectation you need to dig deep on this one and do the work to diagnose it.

The native code starts here https://github.com/thebergamo/react-native-fbsdk-next/blob/d04c9af956d06ff44200330bab4c4a6c05ff9d57/ios/RCTFBSDK/core/RCTFBSDKAppLink.m#L38

This is not a use case I personally use so I won't have time to help, I'm not sure if there are special things to be careful with regard to installation to use deferred app links or anything but I'd check that, then open the app via Xcode and set a breakpoint or add logging statements and watch them, hopefully that let's you see the problem.

I'm happy to help merge + release any reasonable PR you come up with that fixes the issue if you can discover the root cause

**Comment by tranducduong1994** [comment]
@mikehardy . 
Finally, I found out the root cause of the issue. User must allow my app and facebook app to track user's activity ( user can setup in Privacy > Tracking in IOS 14+ ). That why it worked on android as well, cuz Android don't require this permission

**Comment by mikehardy** [comment]
Oh that's really interesting! Thanks for posting back. The App Tracking Transparency stuff is all new and pretty subtle.

I added that to the troubleshooting section https://github.com/thebergamo/react-native-fbsdk-next/commit/2614385e127455488f154bfef5a6f5d157080085

**Comment by sarafcredable** [comment]
https://github.com/thebergamo/react-native-fbsdk-next/issues/234

**Comment by b8ne** [comment]
@mikehardy @tranducduong1994 I'm just implementing this at the moment so only going through these issues now.  I completely understand that you can only work on areas that you have time for, but hoping to get some further background info that may help.  I've installed the base sdk without any ATT permissions and I am still getting the automatic events show up.  In the FB event manager the Overview tab appears to show all events, even in testing, I just have to wait a few hours for them to show.  Test events are only working once the app is in testflight.  In Test events i can see the `fb_mobile_request_deferred_deep_link` but none of the deep link validation tools work, and the link is showing as undefined.
Everything I've read about ATT permission is when sharing user IDs across companies, I am not, and also have FIrebase and RevenueCat setup fine already without ATT, so I'm not sure why ATT is needed for FB?  From your experience, is it just the FB validation and testing features that require it?  Do you think your app and sdk implementation would work fine in production without it?

**Comment by professorkolik** [comment]
@b8ne were you able to validate deeplink?
