### ISSUE TITLE
Could not find module 'FBSDKCoreKit' for target 'arm64-apple-ios-simulator' on M1

### ISSUE THREAD

**Issue by a7med-mahmoud** [thebergamo/react-native-fbsdk-next#113]
## 🐛 Bug Report
When I try to run the app or build it in Xcode I get this error:
Could not find module 'FBSDKCoreKit' for target 'arm64-apple-ios-simulator'

## To Reproduce
Tr

## Expected Behavior
To build correctly without problems

## Environment
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 7.26 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /var/folders/w0/l8rl8d5s5cxbhp31knld_g4c0000gn/T/yarn--1633993209862-0.40993660202642657/node
    Yarn: 1.22.11 - /var/folders/w0/l8rl8d5s5cxbhp31knld_g4c0000gn/T/yarn--1633993209862-0.40993660202642657/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 2021.09.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by mikehardy** [comment]
It definitely builds on an M1, I did it just this weekend while testing some other things.
M1 builds are tricky though. Examine this stuff I have to do with ARCHs in order for Xcode to compile and link things - you should try some of these strategies:

https://github.com/invertase/react-native-firebase/blob/aabb07595f6c8b4e86f20f3d6ebfcb7e91a1819a/tests/ios/Podfile#L52-L54

and one last trick during compile - the VALID_ARCHS here:
https://github.com/invertase/react-native-firebase/blob/aabb07595f6c8b4e86f20f3d6ebfcb7e91a1819a/tests/package.json#L60

I'm going to close this, because this is not a problem with this module specifically, though this one is triggering it. It's a general problem with Xcode compiling and linking things. It's subtle to fix but hopefully those links help
