### ISSUE TITLE
Nothing gets returned to the React app on Android

### ISSUE THREAD

**Issue by LPitonakova** [thebergamo/react-native-fbsdk-next#126]
Hello, I would very much appreciate a tutorial on how to make this library work on Android. I have tried following the "Android Studio setup" from here https://developers.facebook.com/docs/android/getting-started/

I also followed the Quick Setup which gives me code exactly for my Facebook app with the tokens etc. 

I also looked at the Facebook Login Tutorial for Android https://developers.facebook.com/docs/facebook-login/android/ and did the extra steps there (although I think they shouldn't be needed?)

Is there anyone who got this working on Android recently and could they give me a check list of things please?

Here is the issue: When I click on the Login button in my RN app, it opens the Facebook app and I login. Then it returns back to my RN app. However, the `onLoginFinished` of my `<LoginButton>` is never called. The button looks exactly the same and I am not getting any data. What am I missing?

My Facebook app is currently in "nonlive" mode and I have added myself as a developer and tester to it. I am running my RN app in debug mode.

**Comment by mikehardy** [comment]
Does the example app work for you if you put your facebook-app-id in the android strings.xml per example readme ?

https://github.com/thebergamo/react-native-fbsdk-next/tree/master/RNFBSDKExample

It *should* work (I hope it does, have not checked it recently but it used to work and no one has complained recently...)
If it does work then I'm not sure but I'd compare project files between the two. Maybe in AndroidManifest.xml the app launch mode (should be singleTask) or something like that

**Comment by LPitonakova** [comment]
Hi Mike, thanks for the answer.. I did check your project and noticed that you are still using jcenter instead of maven. I recently switched my project into maven as jcenter is set to be deprecated in February 2022.

I am confused right now because I added jcenter into my dependencies to match your build.gradle, rebuilt the app and the login started working. I wanted to make sure that this was the problem so I removed jcenter again, rebuilt the app, and it's still working (???)

I also found in the official documentation (https://developers.facebook.com/docs/android/getting-started/) that tells you how to declare Facebook SDK's dependency on Maven. I am confused by 1. Where to put the code , 2. What goes into `<version>PUT_LATEST_VERSION_HERE</version>` - do you think this is important at all for using `react-native-fbsdk-next`?

**Comment by mikehardy** [comment]
jcenter will be available in read-only mode indefinitely, they have changed their stance, you may observe their latest update: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

That said, removing jcenter is the right thing to do. Your test implies that something in your build set up was cached and incorrect if removing it again no longer has an effect. In those situations you might like `npx react-native-clean-project` - I use it when I have mysterious issues (and I've contributed to it, it's very thorough and useful...)

Our README here is particular about skipping certain things that facebook says to do, because we have it in the module. I believe following our example app (while recognizing it's still on react-native 0.64 so is a little out of date - for example, the jcenter thing) is best practice.

You can see we have this in the module already https://github.com/thebergamo/react-native-fbsdk-next/blob/609c56f7ab06fdf7e8891e21f490c47c3c65af55/android/build.gradle#L47-L52

Follow our README, check our example is how I'd do it

I'm going to take "it's still working" to indicate the module is good, and the issues list is in general for tracking things that will result in changes to the module, whereas this will not - so I'm going to close it, but hopefully this info is helpful

**Comment by LPitonakova** [comment]
Hi Mike, yes for sure it's great that you are keeping this working. Thanks for the detailed response.

One thing that confused me about your Android documentation was that in your Readme, section 3.1., you say to follow the Getting Started guide. In my opinion, Facebook's documentation has always been pretty bad and this is no different. There is a lot of steps you could try to follow and I think my mistake was to follow too many of them and add too many dependencies / things to my project. By looking at your app, I removed all the uneccessary things, re-built the whole project and it worked.

So, in my opinion, it would be more clear to just say which steps exactly to follow from their documentation. Maybe it's just me, I do tend to overcomplicate things sometimes :D

**Comment by mikehardy** [comment]
I am the same way and I agree ;-)
Since you literally just did this, you will honestly be the best person to specify the exact / minimal steps to do, I no longer have perspective on it. If you hit the pencil / edit button on the top right of the readme and propose a PR to the README.md file on the install instructions you could save a lot of future people a headache

Anything sensible at all I can merge it pretty quickly :raised_hands:

**Comment by LPitonakova** [comment]
Sure, would be happy to help - will edit this soon.
