### ISSUE TITLE
Crash on startup on Android 11 only (libc.so)

### ISSUE THREAD

**Issue by gr0x0** [thebergamo/react-native-fbsdk-next#129]
Hello guys,

I'm having a crash issue on app initialization that is affecting only Android 11 users of my app. The stacktrace shows the following error:

_pc 000000000004e30c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)_

Now, it seems to be the same as, according to Facebook, this Audience Network SDK error corrected on version 6.2.0:

https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/android/changelog#6_2_0

Since this happens only on production, I have no way of reproducing it on emulator.

My environment:
    "react": "16.9.0",
    "react-native": "0.62.3",
    "react-native-fbsdk-next": "^4.6.0",

Any ideas?

**Comment by mikehardy** [comment]
Sorry, without a reproduction this could be really challenging, I can't think of anything other than:
- research, but internet search turns up nothing useful for me
- check the code for that fix on facebook audience network (a different SDK) which appears to be closed source, so not sure what the mitigation is/was
- update facebook-android-sdk so that we are using the most current one

Well at least for that last one I have you covered, going to merge and release this as soon as I finish tidying up the example #127 

I know that the older version of the SDK that we are on did not even support targetSdk 31 (Android 11) without crashing, I wouldn't be surprised if it had some other issue (like a startup crash) that is fixed as well, but I have no concrete knowledge of same

**Comment by gr0x0** [comment]
I do think that updating facebook-android-sdk would be the way to go. 

So glad to know an update is on the way! I'll be waiting for that then.

**Comment by mikehardy** [comment]
Just launched v6 here, which includes new underlying facebook-ios-sdk v12, and is of course a bit later than the v5 here a few days ago, which brought in the new android facebook-android-sdk v11. Hopefully that gets things sorted.

There's no action for the repo here as we don't have a reproduction, but if you can come up with a reproduction scenario we can of course reopen it, or even better if you posted a PR if there was a reproduction and you found the solution :)

**Comment by gr0x0** [comment]
I upgraded to v6 and the crash persisted. So I went on and took out all the facebook sdk of my project to see if the crash went away, but nothing changed, so i can say with some certainty that the problem is actually not related to facebook sdk or this lib.

Searching a lot more, found out this is a recurring bug that may be related to Android sdk 30, so I'm focusing on that departament now.

Thx anyway, mike :)
