### ISSUE TITLE
How to setAutoLogAppEventsEnabled(true)

### ISSUE THREAD

**Issue by mifi** [thebergamo/react-native-fbsdk-next#142]
I'm struggling to understand how `setAutoLogAppEventsEnabled` works now. Looking at [GDPR compliance](https://developers.facebook.com/docs/app-events/gdpr-compliance/) docs, there is a function `setAutoLogAppEventsEnabled(true)` that can be called to re-enable this after asking for consent, but I cannot find that function anywhere here. Inside [RNFBSDKExample](https://github.com/thebergamo/react-native-fbsdk-next/blob/176f71989e667360d59d4d68c7197dbfd11cf5a4/RNFBSDKExample/android/app/src/main/AndroidManifest.xml#L42) I can see that `AutoLogAppEventsEnabled` is set to false for Android and iOS, so I'm thinking that will turn off the auto logging. How would I enable the auto logging in code after getting a consent? Maybe this is actually a feature requests to expose that function in `react-native-fbsdk-next`?

**Comment by mikehardy** [comment]
Interesting. Doesn't appear to be exposed here at all. The library was long long long dormant under the facebook org and the focus here since the move was primarily just getting back to current with regard to SDK versions period, much less exposing new functionality. We're current now! So let's go.

Needs two new `@ReactMethod` on native side just below here named setAutoLogAppEventsEnabled and getAutoLogAppEventsEnabled, shaped about like this but with boolean arg calling the API the mentioned in the GDPR compliance doc you linked:

https://github.com/thebergamo/react-native-fbsdk-next/blob/176f71989e667360d59d4d68c7197dbfd11cf5a4/android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java#L61-L69

and here

https://github.com/thebergamo/react-native-fbsdk-next/blob/176f71989e667360d59d4d68c7197dbfd11cf5a4/ios/RCTFBSDK/core/RCTFBSDKSettings.m#L51-L54

Expose it in JS following this pattern here:

https://github.com/thebergamo/react-native-fbsdk-next/blob/176f71989e667360d59d4d68c7197dbfd11cf5a4/src/FBSettings.js#L62-L70

Add type here

https://github.com/thebergamo/react-native-fbsdk-next/blob/176f71989e667360d59d4d68c7197dbfd11cf5a4/types/FBSettings.d.ts#L20-L23

Add mock def for it (could probably add setAppID while in there)!

https://github.com/thebergamo/react-native-fbsdk-next/blob/176f71989e667360d59d4d68c7197dbfd11cf5a4/jest/mocks/index.js#L60

Add a method to the example that reverses the state by querying it and setting it to the opposite, and add a button and text in the example around here https://github.com/thebergamo/react-native-fbsdk-next/blob/176f71989e667360d59d4d68c7197dbfd11cf5a4/RNFBSDKExample/App.js#L59-L67

text shows current state, button calls the method to toggle it

Separately: reading the docs you linked we may need repair on the way we handle GDPR delayed initialize. I'm not sure we're calling all the SDK methods correctly for the GDPR case. On android do we do:

```
FacebookSdk.setAutoInitEnabled(true);
FacebookSdk.fullyInitialize();
```

on iOS do we do:

```
[FBSDKSettings setAutoInitEnabled: YES ];
[FBSDKApplicationDelegate initializeSDK:nil];

```

I'm not sure, it bears examination in order to really respect the users and use the SDK correctly

I provide all this information because you may be unfamiliar with module structure. The implementation is easy. The time-consuming part is testing. I won't have time to do the testing, which implies I don't have time to do the change, you'll need to roll your sleeves up and do it. Probably 1-2 hours ?

Strongly suggest doing the implementation on a fork/clone of this repo on github that you push, and then reference in your work project's package.json by git reference - that way you know you're facebook app ids and everything are all set up and you are productive immediately

Note that git references in package-lock / yarn.lock **go stale** after adding them. In order to update them after you push a change you need to `yarn add miji/react-native-fbsdk-next#branchname` again, that fetches the new commit hash, then rebuild retest

You may also try using the example app but note that it has the same problem - it references the core module by git reference to github with no fancy tricks. So to develop using it you have to copy your changes from parent directories into example node_modules each time. I actually do this, with a just a command line that I run and re-run etc, so it's your choice

Happy to collaborate if you run in to problems, but this is hopefully straightforward, a great contribution if you post a PR

**Comment by mifi** [comment]
Thanks for the detailed explanation! Good to know that I'm not misunderstanding. Of course I don't expect you to do the job, I'll try to do editing of node_modules and patch-package and see if I can create a PR if I get things working.

**Comment by diegotsi** [comment]
hey @mifi, are you working on this? I need this too, maybe i can help you

**Comment by mifi** [comment]
Hi. I tried but didn't manage to finish, things got messy because this code is written in typescript and needs transpiling, so patch-package didn't work out.

This is how far I got:
```diff
diff --git a/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java b/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java
index a97e908..ec73e49 100644
--- a/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java
+++ b/node_modules/react-native-fbsdk-next/android/src/main/java/com/facebook/reactnative/androidsdk/FBSettingsModule.java
@@ -67,4 +67,13 @@ public class FBSettingsModule extends BaseJavaModule {
     public static void setAppID(String appID) {
         FacebookSdk.setApplicationId(appID);
     }
+
+    /**
+     * Set autoLogAppEventsEnabled
+     * @param enabled enabled
+     */
+    @ReactMethod
+    public static void setAutoLogAppEventsEnabled(boolean enabled) {
+        FacebookSdk.setAutoLogAppEventsEnabled(enabled);
+    }
 }
diff --git a/node_modules/react-native-fbsdk-next/ios/RCTFBSDK/core/RCTFBSDKSettings.m b/node_modules/react-native-fbsdk-next/ios/RCTFBSDK/core/RCTFBSDKSettings.m
index 342551c..eb9ed14 100644
--- a/node_modules/react-native-fbsdk-next/ios/RCTFBSDK/core/RCTFBSDKSettings.m
+++ b/node_modules/react-native-fbsdk-next/ios/RCTFBSDK/core/RCTFBSDKSettings.m
@@ -53,4 +53,10 @@ - (dispatch_queue_t)methodQueue
   [FBSDKSettings.sharedSettings setAppID:appID];
 }
 
+ RCT_EXPORT_METHOD(setAutoLogAppEventsEnabled:(BOOL)enabled) 
+ { 
+   [FBSDKSettings.sharedSettings setAutoLogAppEventsEnabled:enabled]; 
+ } 
+
+
 @end
diff --git a/node_modules/react-native-fbsdk-next/src/FBSettings.js b/node_modules/react-native-fbsdk-next/src/FBSettings.js
index 6ead710..588cbca 100644
--- a/node_modules/react-native-fbsdk-next/src/FBSettings.js
+++ b/node_modules/react-native-fbsdk-next/src/FBSettings.js
@@ -12,7 +12,7 @@
 'use strict';
 
 import {Platform} from 'react-native';
-import {isDefined, isString} from './util/validate';
+import {isDefined, isString, isBoolean} from './util/validate';
 
 const Settings = require('react-native').NativeModules.FBSettings;
 
@@ -68,4 +68,13 @@ module.exports = {
     }
     Settings.setAppID(appID);
   },
+    /**
+   * Set autoLogAppEventsEnabled
+   */
+  setAutoLogAppEventsEnabled(enabled: boolean) {
+    if (!isBoolean(enabled)) {
+      throw new Error("setAutoLogAppEventsEnabled expected 'enabled' to be a boolean");
+    }
+    Settings.setAutoLogAppEventsEnabled(enabled);
+  },
 };
```

**Comment by mikehardy** [comment]
It is not a barrier to have patch-package against a typescript lib, I do this a lot. This module is not in typescript though, it's just post-processed anyway, for compatibility

anyway, you want a post-install that does patch-package then `cd node_modules/react-native-fbsdk-next && yarn`

(usually you need a `yarn build` or something as well, but this package's package.json defines "prepare" as `bob build` so once the package's node_modules exist it'll then use the bob package in there to transpile for you, et voila

**Comment by mikehardy** [comment]
oh, and after making changes `yarn prepare` again to re-build so it's ready for consumption, so:
- add that to your package.json postinstall
- dev cycle is make changes in node_modules/react-native-fbsdk-next, yarn prepare in there, re-check, repeat
- done developing to make changes persistent `cd android && ./gradlew clean` (or the diff is not minimal) then `npx patch-package react-native-fbsdk-next`

**Comment by mifi** [comment]
> It is not a barrier to have patch-package against a typescript lib, I do this a lot. This module is not in typescript though, it's just post-processed anyway, for compatibility

https://github.com/thebergamo/react-native-fbsdk-next/blob/d2e894f244faa2e39d56bf0206174b8540e36b50/src/FBSettings.js#L24

afaik `getAdvertiserTrackingEnabled(): Promise<boolean>` is typescript, or am i missing something?



> oh, and after making changes `yarn prepare` again to re-build so it's ready for consumption, so:

thanks for the input, that's good to know, I fell off somewhere there when I tried the other day. unfortunately I don't have time right now to look more into it but if @diegotsi can figure it out, that's great! maybe we could document a working local development flow in the readme also, to make it easier for people to contribute

**Comment by mikehardy** [comment]
That's flow I think, the files are .js - if they have typing, that's flow. This was a facebook module before and they're a flow shop since long before typescript had wide adoption
Now of course typescript has won, so it's unfamiliar to see flow and we should be in typescript, but there's history for you ;-)

**Comment by diegotsi** [comment]
I will check it @mifi

**Comment by Voltron369** [comment]
You just add FacebookSdk.setAutoInitEnabled(true) as the first line of initializeSDK() in FBSettingsModule.java

Then it's cross platform GBPR.  Just set
 <meta-data android:name="com.facebook.sdk.AutoInitEnabled"
           android:value="false"/> for android
<key>FacebookAutoLogAppEventsEnabled</key>
<false/> for iOS

then call  Settings.initializeSDK() when you have permission

**Comment by tharwi** [comment]
Hi, is there any progress in adding the functionality?

**Comment by mikehardy** [comment]
@tharwi as an open source project, you are the developer, not the user. So if you need progress on something, and don't see progress, there likely will not be progress unless you take it up

**Comment by RicardoDolNL** [comment]
> @tharwi as an open source project, you are the developer, not the user. So if you need progress on something, and don't see progress, there likely will not be progress unless you take it up

He was just asking if there was progress, not that weird of question to ask after several months.
There is a big difference between using a project and working on the project itself. Not everyone has the skills to work on it and they instead are very glad that they can make use of the project. While I do understand you'd probably get a lot of these questions, you could have just said 'No, no update yet and I also have no indication as to when'. It's a bit friendlier towards someone else instead of saying 'no fix it yourself'.

**Comment by mikehardy** [comment]
I can understand your desire to mollify someone, but I just re-read my comment and I stand by it. There's no code fairy, and there are no secret updates. We're in this together in the general sense, but in this specific sense it's "if you need it, you need to figure out how to do it, or wait for someone else to do so"

**Comment by bonesyblue** [comment]
Hi all 👋 
I've created a PR (#380), which exposes **setAutoLogAppEventsEnabled** in addition to **setAppName**, **setGraphAPIVersion** & **setAdvertiserIDCollectionEnabled**. I've also added some documentation to ease the transition from `expo-facebook` to this module. Looking forward to your feedback!
