### ISSUE TITLE
Login Failed After Second Attempt in IOS  

### ISSUE THREAD

**Issue by nkutechologies** [thebergamo/react-native-fbsdk-next#148]
Help Please to solve this problem.
When i login in second time this error occured in IOS .I also added a new graph request but i doesn't work with that.
 WARN  Possible Unhandled Promise Rejection (id: 15):
Error: Login Failed

**Comment by mikehardy** [comment]
Use try/catch blocks to catch your promise rejections
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by nkutechologies** [comment]
i've implement the try catch block in my code, but the problem is persistant, and i've tried it several times, after 3 to 4 times, it gives me the data, but in between that it always show me that login is failed in ios case. Before that, i had a problem in android, that user cancelled the sign in process, i just sort it out, but the problem in ios is persistant. I don't know what to do here

**Comment by mikehardy** [comment]
I'd start with reading how to ask good questions, and producing an App.js that may be dropped in anyone's facebook configured project (like...our example app) so people can help. Otherwise no one can help

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
