### ISSUE TITLE
Where do I set de Pixel ID for my App

### ISSUE THREAD

**Issue by gustavolsilvano** [thebergamo/react-native-fbsdk-next#157]
I have the App Id, but where do I set de Pixel ID to be tracked on Facebook Manager?

**Comment by mikehardy** [comment]
Sorry - no idea, you'll have to consult the upstream documentation. I'm not even sure what Pixel ID is, so you already know more than I do ;-). If/when you figure it out, if there is some update to the documentation that would help future people (and educate me/us as maintainers) - hitting the edit button on the README and making a docs PR would be really helpful

**Comment by rnike** [comment]
in my experience the Pixel ID is for web

https://developers.facebook.com/docs/facebook-pixel/advanced/advanced-matching/

**Comment by gustavolsilvano** [comment]
Thank you @rnike. I've came to the same conclusion in my research. It's just that facebook is not so clear about this.

**Comment by swattupdev** [comment]
can pixel be integrated with the react native apps with react-native-fbsdknext? it's just I am finding it hard to find proper documentation related to it.

**Comment by salihboshnak** [comment]
hi All

i did some research for the past 2 weeks about this
like said before in this thread facebook Pixel is for web, in appliations the facebook pixel cant be integrated

in order to be able to run adCampains and build audience for your application
you need to add the application in the facebook developer, and verify it (all is explained in the facebook Docs)
after you finish the APP adding process
you will get and APP_ID 
so when you implement the APP events, you need to configure your react native project's android and ios files
for example: in ios you add the APP_ID in the info.plist file along with other parameters
and one step is to add your APP_ID 
thats how the event triggered from your app is finding its way into the event manager

NOTE: for ios starting from ios 14 you need to get a consent from the end user to enable advertiser tracking
otherwise the trackingAdvertising will be set to FALSE by default
