### ISSUE TITLE
Application becomes much slower when lib is installed

### ISSUE THREAD

**Issue by janvandertaelen** [thebergamo/react-native-fbsdk-next#171]
## To Reproduce
Install package. Application becomes much slower on iOS. In particular Scrolling through a SectionList

## Expected Behavior
No performance impact

## Code Example
After installing application becomes slow 

## Environment
react: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2

**Comment by mikehardy** [comment]
Hi there, what version of *this* module? What version of facebook-ios-sdk is used (check Podfile.lock)

Note prior issues, android but may be similar in iOS? Unknown

https://github.com/thebergamo/react-native-fbsdk-next/issues?q=is%3Aissue+performance

https://github.com/thebergamo/react-native-fbsdk-next/issues/90
https://github.com/thebergamo/react-native-fbsdk-next/issues/90#issuecomment-906943570

What features of the SDK are you using?
Have you checked https://github.com/facebook/facebook-ios-sdk/ issues + PRs list?
Does it reproduce when just using facebook-ios-sdk native? I'm not sure how this wrapper could cause frame drops in other words, I think this will be an underlying bug if it is not already fixed.

**Comment by mikehardy** [comment]
https://stackoverflow.com/help/how-to-ask

**Comment by janvandertaelen** [comment]
just using it to log events. When i use react-native-fbsdk we have no problems was using that till now just swapped with this library and that's when i noticed a performance drop. Currently using v6.2.0 of the react-native-fbsdk-next

**Comment by mikehardy** [comment]
:thinking: "just using it to log events", "just" is a dangerous word, technically speaking, it's not precise enough.
The issue link I included mentioned "auto logging events", perhaps there are multiple ways to log events, that is, automatically vs manually, and something about automatically is not working?
The "big feature" that react-native-fbsdk-next brings in vs react-native-fbsdk is really just that we forward-ported to the new SDKs once react-native-fbsdk was archived.

That strongly implies there is some regression in facebook-ios-sdk, but as with all assertions it requires testing + reproductions to isolate (and then fix). That's the path forward I think, if you have time to pursue it

Otherwise, at minimum this is now open for others to collaborate on
