### ISSUE TITLE
iOS Events Manager

### ISSUE THREAD

**Issue by datoon83** [thebergamo/react-native-fbsdk-next#174]
I've an issue on our production app whereby any Events are not published to Events Manager.  However, in TestFlight the exact same build works fine and we receive events within Events Manager.

Has anyone got this working within their app?  

Android is totally fine, but iOS doesn't work.

**Comment by mikehardy** [comment]
Hello! I think it's strange to say "iOS doesn't work" when you mention explicitly that it works on TestFlight builds. That's a very very curious difference that TestFlight builds work but "production app" doesn't work.

What *exactly* is the difference between your TestFlight build and your "production app"? I ask because for my apps, the TestFlight build *is* the production app, just not released entirely to production yet. All the configs are the same. All of the bits are the same. Only the set of users able to use it is different.

So for my situation at least I don't recognize a difference between "TestFlight build" and "production app", they're equivalent. So then a statement where it works for a "TestFlight build" means to me: it's working.

Really strange...

:thinking:

**Comment by rnike** [comment]
We are using it on iOS production app and it's working fine, have you followed the [official documentation](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios)?

Make sure you have followed the steps below: 
- Step 1: Configure Your Facebook App
- Step 2: Link your Ad Account
- Step 3: Set Up Your Development Environment
- Step 4: Register and Configure Your App with Facebook
- Step 5: Configure Your Project
- Step 6: Connect Your App Delegate and Scene Delegate

**Step 6** might be confusing because the example is written in swift and also using `Scene Delegate` which isn't in regular react-native project, here below is how we implement it(we are not using `Scene Delegate`): 

```objc
// AppDelegate.m

//  ⬇  import this ⬇
#import <FBSDKCoreKit/FBSDKCoreKit.h>

// ... other imports ...

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  //  ⬇  add this ⬇
  [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];

  // ... other code ...
}

// ... other code ...

//  ⬇  rewrite this method ⬇
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  BOOL fbHandled = [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options];
  BOOL rctHandled = [RCTLinkingManager application:application openURL:url options:options];

  return fbHandled || rctHandled;
}

// ... other code ...

```

**Comment by datoon83** [comment]
I've spent some more timing looking at this, and trying to change code...  

It looks as though there are a number of issues raised in the Facebook iOS SDK github repository with regards to this:
https://github.com/facebook/facebook-ios-sdk/issues/1937
https://github.com/facebook/facebook-ios-sdk/issues/1957

We bumped to 6.2.0 of this library to run the latest Facebook SDK's.

@rnike - I was sure whether Step 3 was really necessary because this package pulls the relevant SDK's in anyhow?

@mikehardy - I know I'm at a loss too, as our binary to TestFlight is the same as Production 😞.

**Comment by datoon83** [comment]
@rnike 

I have the following code:
```
useEffect(() => {
    const changeListener = AppState.addEventListener(
      'change',
      async (nextAppState) => {
        if (Platform.OS === 'ios' && nextAppState === 'active') {
          const trackingStatus = await getTrackingStatus();
          const isEnabled = (result: TrackingStatus): boolean =>
            result === 'authorized' || result === 'unavailable';
          Settings.setAdvertiserTrackingEnabled(isEnabled(trackingStatus));
          Settings.initializeSDK();
        }
      },
    );

    return () => {
      changeListener.remove();
    };
  }, []);
```

Do you know what version of this package you are using?  I wonder whether it's linked to the underlying Facebook SDK that I'm using now.

Thanks for the help btw...

**Comment by rnike** [comment]
We are currently on `7.0.0-beta.2`, but I believe `6.1.0` will still work as well (our last version is on 6.1.0), haven't tested on `6.2.0`.

About the `AppState.addEventListener( 'change', callback)` in your code, as my experience, the callback will not be fired on the first start of the app.

So far that's all I can do, if the issue still exists, we will need more information (build environment, package versions, etc).

**Comment by datoon83** [comment]
We managed to get this working in TestFlight last night, we'll release later this week hopefully.

I made the following changes:

1. Moved the initializeSDK to a useEffect in the App.tsx
2. Upgaded to 7.0.0-beta.4
3. Removed an old openURL in our AppDelegate for iOS 8.x or older
4. I enabled AEM reporter - as per the documentation thanks - @rnike
