### ISSUE TITLE
Build fails on iOS on 7.3.1 (M1 Silicon)

### ISSUE THREAD

**Issue by yemd** [thebergamo/react-native-fbsdk-next#210]
I upgraded from 7.2.0 to 7.3.1, and it seems that the new Expo plugin is messing things up, 

## 🐛 Bug Report

I upgraded from 7.0.1 to 7.3.1, and it seems that the new Expo plugin is messing things up.

## Error
The following build commands failed:
        PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/user/Library/Developer/Xcode/DerivedData/electra-efhopmcbavxoswdwpxqrefpzlblb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-0C645E84D737C4B3EF4A9A92FB79B97C.sh (in target 'FBReactNativeSpec' from project 'Pods')
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'ExpoAdapterFBSDKNext' from project 'Pods')
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoAdapterFBSDKNext' from project 'Pods')

## To Reproduce
Create a new reactive native app, use expo modules, add fbsdk, build

## Expected Behavior
Build passes

## Environment
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 100.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.02.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:

**Comment by mikehardy** [comment]
> Create a new reactive native app, use expo modules, add fbsdk, build

Can you list out the exact commands you use to reproduce this, every command + argument? That would really help

@giautm  - possibly of interest - seems the expo plugin might break builds for expo users but I'm not sure what it could be until I get a full repro

**Comment by giautm** [comment]
The Expo adapter was written in Swift. So please make sure you have latest version of Swift SDK (5.4 is required version).

I dont have a Mac M1 for testing right, but looking for you repo to send to someone able to test.

**Comment by mikehardy** [comment]
I have an M1 I can do build testing on no problem, but I have literally zero expo experience, I will need the exact list of steps to reproduce

**Comment by giautm** [comment]
> The following build commands failed:
PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/user/Library/Developer/Xcode/DerivedData/electra-efhopmcbavxoswdwpxqrefpzlblb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-0C645E84D737C4B3EF4A9A92FB79B97C.sh (in target 'FBReactNativeSpec' from project 'Pods')
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'ExpoAdapterFBSDKNext' from project 'Pods')
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoAdapterFBSDKNext' from project 'Pods')

This error is not really helpful; So, can you share full build log? @yemd

**Comment by AlexandreLage** [comment]
I am also facing this error.

**Comment by mikehardy** [comment]
@AlexandreLage not a useful report, there is nothing actionable in this issue if you read the comments
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
https://medium.com/hackernoon/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

Until someone provides *actual information* this stays closed because there's nothing to do, sorry

**Comment by giautm** [comment]
Now, I also have an M1 chip for testing, if you facing the issue, please attach the build error log, then I will take a look. :D

**Comment by poojagupta-simformsolutions** [comment]
I am facing same issue with 8.0.0, has anyone found any work around for the same?
I am having 0.68.1 RN version.

**Comment by mikehardy** [comment]
We can't find a work around because people keep submitting low quality issue details and comments.
Please please please imagine *you* are some random person on the internet, donating their time to help other random people on the internet for who knows what reason.

And someone comes to and says "I am facing the same (poorly specified, no reproduction) issue (except now on a different version)? Anyone have a solution?

Sure, we have lots of solutions. **but we don't know what your problem is**

Quality issue reports! Honest work to specify your problem. You do that, we help you

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
https://medium.com/hackernoon/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b
