### ISSUE TITLE
MessageDialog.show not working on iOS

### ISSUE THREAD

**Issue by omergilboa** [thebergamo/react-native-fbsdk-next#217]
## 🐛 Bug Report

`MessageDialog.show` in `iOS` does not work.

## Expected Behavior

Open the Messenger app's dialog for sending a link via private message.

## Code Example

```
await MessageDialog.show({
  contentType: 'link',
  contentUrl: 'https://facebook.com',
});
```

## Environment

```
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 4.11 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: Not Found
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

using `react-native-fbsdk-next@4.3.0`
using `react-native-fbsdk@2.0.0`

**Comment by omergilboa** [comment]
`react-native-fbsdk` is installed as dependency but not used. we use only `react-native-fbsdk-next`.

i run my app on `iPhone 12`, software v: `15.1.1`. and when pressing on button to call `MessageDialog.show`, nothing happens. same code working fine on `android`.

i'm not sure what all your specific questions means.. Xcode console? logging statements in native code?

**Comment by mikehardy** [comment]
> react-native-fbsdk is installed as dependency but not used. we use only react-native-fbsdk-next.

That's not okay. Don't do that, I was clear. Auto-linking can still bring in incompatible underlying native SDKs.

My advice stands: react-native-fbsdk is dead, we here (react-native-fbsdk-next) are the successor. Use one, use this one.

If you don't follow it, you are on your own.

Stackoverflow has all sorts of information on getting information from your running app using Xcode. It also has lots of information on how to add logging statements in the objective-c language. If you want to find the root cause of your issue, you must roll up your sleeves and do some digging
