### ISSUE TITLE
Can not share Photo on android (Xiaomi redmi note 10 android 12)

### ISSUE THREAD

**Issue by dungnguyentri3110** [thebergamo/react-native-fbsdk-next#229]
## Expected Behavior
I choose image from react-native-cameraroll and share it to facebook. but i  cannot open the sharedialog to share it. i Dont know why. it just response false can not open.

## Code Example
const onPressShare = async () => {
    try {
      const option: ShareContent = {
        contentType: "photo",
        photos: [
          {
            imageUrl: "file://storage/emulated/0/DCIM/Facebook/FB_IMG_1650338011790.jpg",
            userGenerated: true,
            caption: "Hello motherfucker",
          },
        ],
      }
      const canShow = await ShareDialog.canShow(option)
      console.log("canshow", canShow)
    } catch (error) {
      console.log("share error", error)
    }
  }

**Comment by mikehardy** [comment]
This is a low-quality issue report, sorry. No error messages from native (adb logcat or xcode console) no description of test environment versions in play, anything you'd want if a co-worker came to you and asked this question
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by AlexMubarakshin** [comment]
Hi!

I am using the latest version of react-native-fbsdk-next and I am getting the same issue.

When trying to call `canShow(...)`, getting this error in console:

![err](https://user-images.githubusercontent.com/15522211/167300200-c183946c-0e87-4699-a22a-06342e48f726.jpeg)

**Comment by mikehardy** [comment]
@AlexMubarakshin please paste text, your image paste is incomprehensible to me both on web an mobile.

Enclose in triple backticks or a > if needed as markdown hints

**Comment by AlexMubarakshin** [comment]
> @AlexMubarakshin please paste text, your image paste is incomprehensible to me both on web an mobile.
> 
> Enclose in triple backticks or a > if needed as markdown hints

```log
{"error": [Error: Unable to show the provided content via the web or the installed version of the Facebook app. Some dialogs are only supported starting API 14.]}
```

**Comment by mikehardy** [comment]
@AlexMubarakshin you say "I am getting the same error", the original reporter did not actually report an error, so I am not sure if that assertion is true.

Your error, now that I can read it, is something I haven't seen before. Best next steps are to search for that string in facebook-android-sdk repo (it's also open source) and see where it comes from and under what conditions, then start tracing code from there until you find the answer. This isn't a use case of mine and I haven't seen it before so with apologies I don't have more to offer than a style for finding the root cause, vs an answer
