### ISSUE TITLE
Could not resolve com.facebook.android:facebook-android-sdk:12.+ Problem

### ISSUE THREAD

**Issue by BerkD145** [thebergamo/react-native-fbsdk-next#248]
## 🐛 Bug Report
When I try to get android release I'm getting a error . It was working 3 day ago without a any problem
This is the error
`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:minifyReleaseWithR8'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.android:facebook-android-sdk:12.+.
     Required by:
         project :app > project :react-native-fbsdk-next
      > Failed to list versions for com.facebook.android:facebook-android-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)
`

How can I resolve this problem ? 

## To Reproduce
./gradlew assembleRelease

**Comment by ramazanarslan** [comment]
Same problem +1

**Comment by SaikatTerum** [comment]
Same Issue +1

**Comment by mustafakemalelma** [comment]
Latest version (8.0.2) gives almost the same error but with `facebook-android-sdk:13.+`

```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.android:facebook-android-sdk:13.+.
     Required by:
         project :app > project :react-native-fbsdk-next
      > Failed to list versions for com.facebook.android:facebook-android-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)
```

**Comment by gauravpradhnani** [comment]
Same Issue +1

**Comment by xiaohui-gsv** [comment]
Same issue +1
```
Execution failed for task ':react-native-fbsdk-next:generateReleaseRFile'.
> Could not resolve all files for configuration ':react-native-fbsdk-next:releaseCompileClasspath'.
   > Could not resolve com.facebook.android:facebook-android-sdk:9.0.+.
     Required by:
         project :react-native-fbsdk-next
      > Failed to list versions for com.facebook.android:facebook-android-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml'.
                  > org.apache.http.client.ClientProtocolException (no error message)

```

**Comment by BerkD145** [comment]
I found a solution. It did worked fo me 
Adding `mavenCentral() `to build.gradle(project)

And adding `implementation 'com.facebook.android:facebook-android-sdk:latest.release' `to build gradle on app folder. 

I hope this will work for you too

**Comment by SaikatTerum** [comment]
It's not working @BerkD145 .

**Comment by gauravpradhnani** [comment]
Didn't worked for me as well @BerkD145

**Comment by xiaohui-gsv** [comment]
> I found a solution. It did worked fo me Adding `mavenCentral()` to build.gradle(project)
> 
> And adding `implementation 'com.facebook.android:facebook-android-sdk:latest.release'` to build gradle on app folder.
> 
> I hope this will work for you too

I commented out the `jcenter()` and added the `mavenCentral()`, and it works, I can build android successfully.

**Comment by meowchownow1** [comment]
Same Issue +1

**Comment by SaikatTerum** [comment]
Not working @xiaohui-gsv

**Comment by meowchownow1** [comment]
Didn't worked @BerkD145

**Comment by xiaohui-gsv** [comment]
> Not working @xiaohui-gsv

Error still the same? refer to this [post](https://blog.gradle.org/jcenter-shutdown), there is a solution and troubleshoot in it.
<img width="753" alt="image" src="https://user-images.githubusercontent.com/38554198/167386495-f4a959e9-c0eb-4141-ace7-079663abb7d8.png">

**Comment by SaikatTerum** [comment]
My file Is look like this
![Uploading Screenshot 2022-05-09 at 3.25.41 PM.png…]()

**Comment by IsmaelMiber** [comment]
Guys, you have to add `mavenCentral()` in each place `jcenter()` is exist, I didn't remove `jcenter()` because when removed it, some errors happened.

**Comment by SaikatTerum** [comment]
Guys, @IsmaelMiber is right. Ialso tried that before seeing his comment.  you have to add mavenCentral() in each place jcenter() is exist, I didn't remove jcenter() because when removed it, some errors happened.

**Comment by xiaohui-gsv** [comment]
In my case, if I keep the jcenter(), the error will still happen, maybe it was due to we use a different Gradle version.

**Comment by AnthonyHaykal** [comment]
Same issue +1
I tried the solutions above, but I still get errors, for example this one:
Problems reading data from Binary store in /private/var/folders/hs/mdyhtn3d6rq6sh8c0y4qgjch0000gn/T/gradle3476956413297884846.bin offset 165763 exists? true

**Comment by gauravpradhnani** [comment]
I am getting same problem after using solution above :-
Execution failed for task ':app:processDebugResources'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Problems reading data from Binary store in C:\Users\Admin\.gradle\.tmp\gradle13814715661237366826.bin offset 752275 exists? true

**Comment by Wanes-Tutunjian** [comment]
Same issue +1 

None of the mentioned solutions worked, I keep getting:

Problems reading data from Binary store in ...

**Comment by BilalYazbek** [comment]
Same issue: Problems reading data from Binary store...

**Comment by Ranay117** [comment]
Same Issue +1

**Comment by milosdelibasic** [comment]
Had same issue, fixed it by changing
`implementation 'com.facebook.android:facebook-android-sdk:[4,5)'`
to
`implementation 'com.facebook.android:facebook-android-sdk:latest.release'`
in **app/build.gradle**
Also updated react-native-fbsdk-next version from 7.3.3 to latest, 8.0.2 which required some updates, I had to add **Client token** to both android & iOS which is required since SDK 13. You can find it in Facebook Developer in your app, Dashboard, navigate to Settings > Advanced > Security > Client token.
**Android:**
in strings.xml add after facebook_app_id
`<string name="facebook_client_token">YOUR CLIENT TOKEN</string>`
AndroidManifes.xml after <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/> add
`    <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>`
after that clean gradle &you  rebuild and it should work.
For **iOS** you add client token in Info.plist for example after FacebookAppId:
	<key>FacebookClientToken</key>
	<string>YOUR CLIENT TOKEN GOES HERE</string>
Hope this helps at least one person since I struggled with it

**Comment by AnthonyHaykal** [comment]
Adding mavenCentral() and then making sure the version in build.gradle is the same as inside node_modules, worked for me.

**Comment by mayank-paryani** [comment]
Had same issue, fixed it by changing
 implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
to
 implementation 'com.facebook.android:facebook-android-sdk:4.30.0'
in app/build.gradle

Because the latest version requires a Client token for both android & iOS and I didn't have a Client Token available with me.

So, after using this 4.30.0 version I am able to build an android project successfully.

Hope this helps at least one person since I struggled with it.

Also, add mavenCentral() in each place jcenter() exists if you haven't already.

**Comment by gauravpradhnani** [comment]
@AnthonyHaykal which version you checked in build.gradle and node_modules.

**Comment by adniltonsantos** [comment]
Same Issue +1

**Comment by gauravpradhnani** [comment]
@AnthonyHaykal working now. thanks a lot.

**Comment by mikehardy** [comment]
First of all: EVERYONE STOP +1'ing issues. I'm serious, maintainers hate that. You have blown up my notifications for the day and it makes github really hard to use.

Add a reaction, never a +1. </rant>

Second, this problem has nothing to do with this module. We don't use jcenter. jcenter has been phasing out for a while, and you should not have it in your build.gradle files anywhere anymore. If you do, because some dependency requires it, that's on you to upgrade to the version(s) where the dependency was removed

#115 #184 is where we did the work here.

So you'll have to find whatever other things are still using jcenter and remove them *but it is not this module*

There is nothing actionable for us here.

This is a huge pain in the butt, I understand (I helped remove it from lots of places myself, and my own apps) but there's nothing we can do. And any time jcenter goes down, this will happen to you, until you remove it

**Comment by spinfomacbook** [comment]
> implementation 'com.facebook.android:facebook-android-sdk:latest.release'

Yes it is working.....

**Comment by mikehardy** [comment]
If you use "latest release"
Then next breaking change, your code will break without you changing a thing
Then there will be another issue like this, with lots of people going "I changed nothing now my code doesn't compile"
Use real versions, at least pin the major like "13+"

**Comment by Eumhongin** [comment]
@moezbaccouche Thank you! it works for me!

**Comment by golditdev** [comment]
> mavenCentral

implementation 'com.facebook.android:facebook-android-sdk:4.30.0'
in app/build.gradle

worked for me

**Comment by mikehardy** [comment]
@golditdev you should be careful with that - they are on version **13.2.0** right now. No idea how old 4.30.0 is but I'd be wary

https://github.com/facebook/facebook-android-sdk/releases

**Comment by iamsethsamuel** [comment]
Just use an absolute version like com.facebook.android:facebook-login:11.1.1

**Comment by mikehardy** [comment]
@iamsethsamuel with apologies, this is objectively terrible advice. There are frequently incompatibilities across major versions, meaning that the version the module code here expects to be using is the major version that it depends on

You may override this because it is open source and you can do anything, but you are likely to then have difficult to debug issues with your app if it even builds at all, and you will also then be responsible for verifying compatibility + bumping the dependency to new versions periodically instead of relying on the module to do it for you.

I would never do that personally, not when the solution is is as easy as 1) staying current with your deps, 2) removing jcenter from your build.

**Comment by praveenstratagile** [comment]
implementation 'com.facebook.android:facebook-android-sdk:15.0.2'

Try this latest version

**Comment by Mecze** [comment]
For some reason, removing jcenter from gradle still tries to resolve the dep from "https://jcenter.bintray.com/"

Mind you, it's not for react, is for the Facebook Unity SDK.

**Comment by mikehardy** [comment]
> "for some reason"

`for FILE in `find . |grep build.gradle`; do echo $FILE; cat $FILE |grep jcenter`

or similar to find the offender

**Comment by hit-cod** [comment]
removing `jcenter()` from android -> build.gradle worked for me. this is how it looks (versions: "react": "18.2.0",  "react-native": "0.69.6",):
```
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }

        google()
        maven { url 'https://www.jitpack.io' }

    }
} 
```

**Comment by louiechristie** [comment]
> > "for some reason"
> 
> ```shell
> for FILE in `find . |grep build.gradle`; do echo $FILE; cat $FILE |grep jcenter
> ```
> 
> or similar to find the offender

The full command to find your jcenter dependencies to remove/update is:

for FILE in `find . |grep build.gradle`; do echo $FILE; cat $FILE |grep jcenter; done

**Comment by jeffreycgy** [comment]
for anyone that searched for this error and came from the top result on google, here's the latest reason https://github.com/facebook/facebook-android-sdk/issues/1345
