### ISSUE TITLE
The login is working in debug apk but not in release apk.

### ISSUE THREAD

**Issue by yg-yash** [thebergamo/react-native-fbsdk-next#263]
I have added hashkeys of both debug.keystore and release.keystore.

Login is working fine in debug apk but when i generate release apk it throws error which is "Login Error : there is an error in logging you into this application. please try again later."

Please help stuck on this issue since 2 days no success.

**Comment by mikehardy** [comment]
With apologies, I hear you are frustrated, but as a maintainer, this issue is nearly content free
https://stackoverflow.com/help/how-to-ask

Check device logs (adb logcat) while doing the login. Reach in to node_modules and add console.logs in javascript, add System.err.println of error message in the underlying SDK responses. Gather all the info you can.

All I can say is: it works for everyone else, including me personally on multiple apps.

That's a really strong signal that you are not configured correctly. Triple check everything again.
If it still doesn't work, make a small toy app (that you don't release publicly, that's fine) and test it so you have a minimal example.

Since it works for everyone else I'm going to close this as not actionable here: it will *not* result in a change in this module. Take the information you've gathered and ask on stackoverflow for general facebook login issues on android I think
