### ISSUE TITLE
'value' is unavailable: introduced in iOS 12. RN: 0.69.x

### ISSUE THREAD

**Issue by raufpratama** [thebergamo/react-native-fbsdk-next#267]
## 🐛 Bug Report

"react-native": "0.69.0-rc.6",
"react-native-fbsdk-next": "^8.0.5",

i got issue when build and run ios app on simulator (iPhone 12 mini, ios 12.4), the error shows as follow:

![Screen Shot 2022-06-06 at 11 15 42](https://user-images.githubusercontent.com/34560036/172093819-fde429f0-5654-4bcd-a15b-2aced6370578.png)

i got this issue since upgrading **react-native: 0.68.x** to **react-native: 0.69.x**, it think this relates to minimum platform ios, since in **react-native: 0.69.x** require minimum platform ios of 12.4 version

## Environment

Run on xcode Version 12.2 (12B45b)

**Comment by mikehardy** [comment]
You are brave! I'm in the react-native release-testers group and with rc6 it's the first time ti's really usable even :-). You closed this, so I'm curious (since release-testers are mostly checking compatibility) - is it working for you now? Are you using old architecture or new architecture? Or did you test both?
