### ISSUE TITLE
LoginManager missing logInWithReadPermissions

### ISSUE THREAD

**Issue by sofiaringstrom** [thebergamo/react-native-fbsdk-next#274]
## 🐛 Bug Report
The loginManager doesn't have the function to login with only read permissions. We don't want the user to grant us to have full write permission, there's no need for it and could potentially scare users of our app. But the LoginManager is missing the logInWithReadPermissions. What are the options here? I can't find anything addressing why it's not available.

## Expected Behavior
Being able to request read permissions.

**Comment by mikehardy** [comment]
Hi there! I hadn't heard of this capability even, so I'm not surprised it is not supported. If this is something your business needs, feel free to propose a PR to add support, we merge+release all reasonable PRs

**Comment by sofiaringstrom** [comment]
@mikehardy Unfortunately, I don't have any experience with Java so I'm not going to be able to do this. 

I did see that Facebook removed this function back in 2019, I'm not sure why. We're just now moving to this package from expo-facebook where this was supported. But we will move on with using `logInWithPermissions` for now.

**Comment by mikehardy** [comment]
Ah I see. Yes it appears that expo-facebook module was seriously out of date: https://github.com/expo/expo/blob/34427758bfce73e53c296f6c8105a34ff7fcdb18/packages/expo-facebook/android/build.gradle#L86-L87

And rather than update it they've just discontinued and pushed users here to use this module via config plugins :shrug: 

If the underlying SDK removed it, then there is nothing to do, we can only wrap functions at the react-native layer that exist in the SDK layer, so it looks like your plan of moving to logInWithPermissions is the right path

Good luck with your project!
