### ISSUE TITLE
Share preview not working 

### ISSUE THREAD

**Issue by adamodusa** [thebergamo/react-native-fbsdk-next#326]
## 🐛 Bug Report

When using the shareDialog to share a link to facebook, the shareLinkContent in the preview is not showing. 

```
const fbShare = async () => {
    const shareLinkContent = {
      contentType: 'link' as "link",
      contentUrl: await generateLink(),
      contentDescription: prayer?.title,
      quote: "something something here",
      imageUrl: prayer?.image,
    }

    console.log('shareLinkContent', shareLinkContent)

    ShareDialog.canShow(shareLinkContent).then((canShow) => {
      if(canShow) {
        return ShareDialog.show(shareLinkContent);
      }
  }).then(
    function(result: ShareDialogResult | undefined) {
      if (result?.isCancelled) {
        console.log('Share cancelled');
      } else {
        console.log('Share success with postId: '
          + result?.postId);
      }
    },
    function(error) {
      console.log('Share fail with error: ' + error);
    }
  );
  }
```

**Comment by mikehardy** [comment]
Hey there 👋  - not saying this to seem rude, but as I'm the only person regularly in the issues lists + making changes here I just need to set expectations that I do not use this module for sharing so this isn't a use case of mine. So I need to set the expectation that unless someone else turns up to help maintain the module that is interested in triage here, you'll probably need to dig in to this personally to look for docs (to set technical expectations) then code (to determine root cause + fix)

I'll happily merge any reasonable PR though, if you discover something that needs a change
