### ISSUE TITLE
Archiving failed for iOS - 

### ISSUE THREAD

**Issue by neerajpk02** [thebergamo/react-native-fbsdk-next#345]
## 🐛 Bug Report
SDK installation is success for both iOS and Android. While archiving the iOS build, we are getting 

'FBSDKShareKit/FBSDKShareKit.h' file not found

Debugging is success and able to run the application live in real devices too. The issue is only with archiving the build.
![Screenshot 2022-11-09 at 7 49 05 AM](https://user-images.githubusercontent.com/87416192/200721199-1a9936d0-3d7a-4e6b-98fa-9f517623be00.png)

## Environment
React Native Version - 0.70.5
Xcode - Version 13.4.1 (13F100)

**Comment by neerajpk02** [comment]
> 
package version  "react-native-fbsdk-next": "^11.0.1"

 - FBSDKCoreKit (15.0.0):
  - FBAEMKit (= 15.0.0)
    - FBSDKCoreKit_Basics (= 15.0.0)
  - FBSDKCoreKit_Basics (15.0.0)
  - FBSDKGamingServicesKit (15.0.0):
  - FBSDKLoginKit (15.0.0):
    - FBSDKCoreKit (= 15.0.0)
  - FBSDKShareKit (15.0.0):

@mikehardy adding these details. This is the details from podlock

**Comment by mikehardy** [comment]
I just verified the last release of my work project, it was *definitely* on v11+ of this module, with v15+ of the facebook-ios-sdk, and it definitely archived and is live in production first via TestFlight then out to all users.

I had / have no problem archiving this module with v11 here.

I do have use_frameworks in my Podfile, perhaps that's something different. I don't know because you haven't provided a reproduction that would include a Podfile that shows the problem.
