### ISSUE TITLE
Unable to track event parameter on facebook event manager consnole

### ISSUE THREAD

**Issue by priyankagupta23pg** [thebergamo/react-native-fbsdk-next#491]
## 🐛 Bug Report
I am not able to see parameters passed from app using below code how can  param values I see on fb console,
on console only getting events count & events name

## To Reproduce
Run below code
## Expected Behavior
while parameter sent along with events should also be displayed

## Code Example

AppEventsLogger.logEvent(AppEventsLogger.AppEvents.ViewedContent, {
"event_name": isIOS?"ios Login screen":"android Login screen",
"event_time": new Date().getMilliseconds(), });

unable to see parameters on Event manager console..Please clarify where I can see these parameter values.Only event name & count is coming

ANdroid & ios both platform same issue

**Comment by mikehardy** [comment]
With apologies this isn't a feature I use and this is an open source repository.
You'll have to alter your expectations of who will do what and revise them to "I will investigate what the cause is and collaborate upstream with facebook-android-sdk or facebook-ios-sdk as needed"

That's the way to move this forward, possibly with a https://stackoverflow.com/help/minimal-reproducible-example based on one of their quickstarts as needed
