### ISSUE TITLE
(iOS) Automatic purchase event is not logging in iOS sdk 17.0.0 

### ISSUE THREAD

**Issue by Tarun24RN** [thebergamo/react-native-fbsdk-next#529]
## 🐛 Bug Report
In iOS facebook automatic logged In-App Purchase event is not logging after updating the library and ios sdk to 17.0.0 .

## Expected Behavior
Subscribe event should come when user purchase subscription in app.

## Code Example
Subscribe event is automatically logged event, no extra code from our side for this event is required.

## Environment
"react-native": "^0.72.0"
"react-native-fbsdk-next": "^13.0.0"

**Comment by OkyDokyApp** [comment]
@Tarun24RN same issue here since upgrading.

I tried downgrading to react-native-fbsdk-next 12.2.0 but I still don't appear to see any attributed purchase events in Meta Ads anymore.

I'm not sure which react-native and react-native-fbsdk-next versions I had when it was working.

Did you get it to work again? If so which versions of react-native and react-native-fbsdk-next are you using?

Thank you in advance!

**Comment by Tarun24RN** [comment]
> @Tarun24RN same issue here since upgrading.
> 
> I tried downgrading to react-native-fbsdk-next 12.2.0 but I still don't appear to see any attributed purchase events in Meta Ads anymore.
> 
> I'm not sure which react-native and react-native-fbsdk-next versions I had when it was working.
> 
> Did you get it to work again? If so which versions of react-native and react-native-fbsdk-next are you using?
> 
> Thank you in advance!

No, still it is not working now I am sending subscribe event from my code with standard parameters and it is showing as standard event on Facebook.
