### ISSUE TITLE
FB SDK version Needs upgrade (from v17.0.3 to v17.1.0)

### ISSUE THREAD

**Issue by yaroslav-bodnar** [thebergamo/react-native-fbsdk-next#555]
Hello, Facebook has been in need of an update to a new version for a long time, and without an update, launching ads for events in the application does not work... Also, Facebook constantly reminds you that you need to update the SDK. Unfortunately, the last update here was 5 months ago, and it's not clear if someone is working on an update now...

That is why I am asking for help, what other solutions can there be to integrate Facebook with React Native, so that it is not necessary to use xcode... Maybe some modules or something else...

**Comment by mikehardy** [comment]
That's odd, I don't see a PR anywhere 🤔  - @yaroslav-bodnar have you tried proposing a PR here to do the update?
It's pretty easy usually, typically not much more than bumping the versions, attempting to compile the example app and seeing what breaks. That's normally just some simple compile fixes then boom, you've got your update

**Comment by imki123** [comment]
Hello, @mikehardy. I found facebook-ios-sdk Release v17.1.0. Please update react-native-fbsdk-next. 🙌
- https://github.com/facebook/facebook-ios-sdk/releases/tag/v17.1.0
- https://github.com/facebook/facebook-ios-sdk/compare/v17.0.3...v17.1.0

**Comment by mikehardy** [comment]
Open a PR please, more effective than pleading...

**Comment by joshmohrer** [comment]
I realize everyone's time is short, especially those gracious enough to contribute to OSS like this. (thank you @mikehardy  and others -- couldn't have done this without you, including your firebase SDK)

**Id like to sponsor the upgrade to the newest SDKs across ios and android.** Please reach me at josh@wave.co to arrange details. This is high priority for me as its disrupted our ads since 17.1 came out.

Thank you :)

**Comment by mikehardy** [comment]
Just to note that I've reached out @joshmohrer but haven't heard back? As mentioned I'm past "very busy" to "ridiculously busy" at the moment but the family understands me working late if it's not all pro bono (I do enough of that with AnkiDroid but that one helps medical students so the family gives me a pass ;-) https://github.com/ankidroid/Anki-Android)

It doesn't look like a difficult upgrade, but the qualification of current repo state + qualification of the new SDKs and doing the release does take an hour or so. Not much more than that at least

**Comment by joshmohrer** [comment]
Gah, sorry @mikehardy  -- replying now
<img width="542" alt="Screenshot 2024-09-26 at 2 35 58 PM" src="https://github.com/user-attachments/assets/decb5441-f335-40ac-9e04-1455c0c07a4c">

**Comment by mikehardy** [comment]
Oh no I'm spammy 😆 . Possibly true, I'm at peace with myself

**Comment by joshmohrer** [comment]
My spam filter just takes itself way too seriously I think

**Comment by mikehardy** [comment]
Hey, so this is done in #557 however I am unable to publish the v13.1.0 release that I just packed up
The semantic release system correctly built and tagged the release and made the changelog but it failed on the `npm publish` step

@thebergamo help! have you changed your 2FA settings on npmjs.com to `auth-and-writes` instead of `auth-only`? Or did you revoke the NPM token that's configured in this repository? I don't have any authority on the npmjs.com react-native-fbsdk-next package nor do I have admin authority on this repo, so I'm not able to resolve this

In the meantime, I suppose you can always rely on the v13.1.0 tag here as a direct github dependency, it should work?

For yarn2+ I think that's something like `yarn add react-native-fbsdk-next@thebergamo/react-native-fbsdk-next#v13.1.0`
for yarn classic I think `yarn add git@github.com:thebergamo/react-native-fbsdk-next#v13.1.0` but I could be wrong
unsure on npm but something similar?

It'll be published on npmjs.com once the NPM auth / token situation is resolved, but until then I've taken it as far as I can - it's good bits on a known good tag at least 🤷

**Comment by thebergamo** [comment]
Oh, if you don't mind I can check this first thing in the morning, tomorrow!!

I will take a look on what happened in npm and maybe I can even try to give you permissions in the npm itself for publishing.

**Comment by thebergamo** [comment]
Alright, I fixed the token, but would need to get hands on my terminal to publish again to npm from the tags as semantic release cannot do it on a retry.

Will do it tomorrow for next ones it should be fine.

Basically npm has new token type specific for automation and it should be enough now to publish again without 2fa (was forced to enable it once I recovered my npm account hehe)

**Comment by mikehardy** [comment]
@thebergamo excellent! That did it, after your invite on npmjs.com so I was a known package maintainer, I was able to do an `npm publish` of the package. So now I think everything is in sync

With luck, the next package publish will be fully auto with the new token as well - I believe I/we will get to test that shortly because facebook-ios-sdk is in the middle of their publishing process for 17.2.0 already (but it isn't on cocoapods yet so we can't use it yet...)

Thanks!

https://www.npmjs.com/package/react-native-fbsdk-next?activeTab=versions

**Comment by joshmohrer** [comment]
Might be specific to the code on my end but the expo config plugin stopped working, app.json stopped recognizing the plug-in:

```

CommandError: Package "react-native-fbsdk-next" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Cannot use import statement outside a module
```

**Comment by mikehardy** [comment]
Hmm @joshmohrer that's obviously unexpected, sorry about that.
There were a couple items in the PR that may have played a part and I can revert them as a stopgap, then exercise the publish with new NPM token at the same time, ideally a win-win. Lemme see
I'm going to extract your comment to a new issue for separate tracking

**Comment by mikehardy** [comment]
@thebergamo publish worked on 13.1.1 🫡 
v13.1.1 has a revert of the two items I think broke the expo plugin, would love feedback
