### ISSUE TITLE
App Freezes During Facebook Login on Android 14

### ISSUE THREAD

**Issue by kiakim01** [thebergamo/react-native-fbsdk-next#580]
## 🐛 Bug Report

Hello,
There is an issue where the app freezes on Android when attempting to log in with Facebook.
When debugging the function, the LoginManager is called, but the freeze happens when logInWithPermissions is triggered.

The issue persists even if the login is cancelled midway.

## Code Example

```
 LOG  1.check LoginManager -> 
{"getDefaultAudience": [Function getDefaultAudience], "getLoginBehavior": [Function getLoginBehavior], "logInWithPermissions": [Function logInWithPermissions], "logOut": [Function logOut], "reauthorizeDataAccess": [Function reauthorizeDataAccess], "setDefaultAudience": [Function setDefaultAudience], "setLoginBehavior": [Function setLoginBehavior]}
```

```Javascript
export const facebookLogin = async () => {
  try {
    console.log('1.check LoginManager ->', LoginManager)

    const result = await LoginManager.logInWithPermissions(['email', 'public_profile'], 'enabled')

    console.log('2.facebook response ->', result)

    if (result.isCancelled) {
      console.log('isCancelled')
      return
    }

    const data = await AccessToken.getCurrentAccessToken()
    if (data) {
      const token = data.accessToken.toString()
      return await socialLogin({socialType: 'FACEBOOK', token: token})
    }
  } catch (error) {
    console.error('Error:', error)
    return
  }
}

```

## Environment

```
  "react-native": "0.73.2",
  "react-native-fbsdk-next": "^13.1.4",
   -
  OS :  Android 14
```

**Comment by mikehardy** [comment]
Apologies - I won't have time to work through this myself and I'm not sure there are any other active maintainers here helping out.

What that means is that the expectation is you'll have to drive this to a root cause, by watching `adb logcat` on the device, checking if it is a difference between real device vs emulator, possibly going in to the native code and adding `android.log.Log.d()` calls before and after API calls to the native facebook-android-sdk and logging out the responses etc

I will happily merge any PRs and get a new release out, I just don't have free time to donate right now for this repo
