### ISSUE TITLE
Project is not building for ios. 

### ISSUE THREAD

**Issue by raza-metalogix** [thebergamo/react-native-fbsdk-next#593]
<img width="402" alt="Screenshot 2024-12-27 at 4 53 39 PM" src="https://github.com/user-attachments/assets/aaa13ad1-ead0-47b9-91dc-94c2c1c2be49" />
<img width="444" alt="Screenshot 2024-12-27 at 4 55 09 PM" src="https://github.com/user-attachments/assets/561e99b6-0a57-407a-88ab-31227e2969db" />
<img width="985" alt="Screenshot 2024-12-27 at 4 56 12 PM" src="https://github.com/user-attachments/assets/0d6dc9b4-beb3-46f8-ba0c-6b5ea401c37a" />

- I follow all the step from guideline  and also from facebook developers for ios sdk docs. 
- Add the Document/FacebookSdk path to search options. 
- pod install && npm run ios
- Then I got 

The following build commands failed:
        CompileC /Users/metalogx/Library/Developer/Xcode/DerivedData/IosFaceApp-hknjmpqmvcylpphbjkfomaooahfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-fbsdk-next.build/Objects-normal/x86_64/RCTFBSDKShareHelper.o /Users/metalogx/Documents/IosFaceApp/node_modules/react-native-fbsdk-next/ios/RCTFBSDK/share/RCTFBSDKShareHelper.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-fbsdk-next' from project 'Pods')
(1 failure)

<img width="720" alt="Screenshot 2024-12-27 at 4 59 16 PM" src="https://github.com/user-attachments/assets/5d42f115-64c5-48a0-8a70-727c351bc56c" />

I would happy or you save my job if you please help me solve this error. I am new to react native so please anyone help me with it.

**Comment by mikehardy** [comment]
Your images are no substitute for using *text* to specify your versions etc, images are a terrible way to communicate troubleshooting information unless they are showing device screenshots or similar, vs code

There will be no change in this repository related to compilation etc though as I'm certain it compiles with current versions of Apple development toolchains and current versions of react-native, so I will close this issue since it isn't actionable here

You should consult our example, and you should consult how we build it via an automated script to see how to properly integrate the module

https://github.com/thebergamo/react-native-fbsdk-next/blob/master/refresh-example.sh

**Comment by raza-metalogix** [comment]
Okay Thank for reaching out to me.
