### ISSUE TITLE
Login not working on pop-up dialogged android devices

### ISSUE THREAD

**Issue by ugrdursun** [thebergamo/react-native-fbsdk-next#70]
Very simple problem to explain:

On some android devices, it redirects you to **browser** to login, login works like charm.

But some of them, some pop-up comes like this:

![login-with-facebook-for-android](https://user-images.githubusercontent.com/23141977/125144826-caf59b80-e127-11eb-8541-c12e6219a44e.png)

And after press "CONTINUE AS XXX" button, nothing happens.

RN 0.61.5
Library: 4.3.0

Any solution for this ?

**Comment by mikehardy** [comment]
Sorry - no idea, what do you see when you add console log statements in the javascript in the node_modules for this module and/or System.err.println()'s in the java in the same ? Curious what the API calls are actually returning and/or if there is anything for us to do.

This will likely have a great deal more related information either on https://github.com/facebook/facebook-android-sdk/ (and related docs) or stackoverflow. Likely related to the work facebook has been doing to allow multiple profiles logged in at the same time (like business account and personal account)

**Comment by nithiniz** [comment]
Same issue

**Comment by mikehardy** [comment]
@nithiniz this issue is pretty old and has insufficient details to reproduce.
You should try our example app, with your app id in it (check the README in example for instructions)
If you can reproduce with the example using your app id, then please post a new issue with complete details
https://stackoverflow.com/help/minimal-reproducible-example
