### ISSUE TITLE
ShareDialog returns isCancelled true when posting successfully

### ISSUE THREAD

**Issue by messycoding** [thebergamo/react-native-fbsdk-next#87]
```
ShareDialog.canShow(shareLinkContent).then((canShow) => {
     if (canShow) {
          return ShareDialog.show(shareLinkContent);
      }
}).then((result) => {
      console.log(result)  // this thing right here is a problem
});
```

The **_result_** in debug mode iOS returns empty object {} if user successfully shared a link but in release mode this returns `{isCancelled: true}`. This issue only happens in iOS release mode like testflights or development exports. Everything works fine on Android and ios DEBUG MODE.

I am expecting that the result should be consistent, empty object when successfully shared and {isCancelled: true} when cancelled.

I am setting the mode to browser ShareDialog.setMode('browser');
ShareDialog.setMode('webiew'); // same result
ShareDialog.setMode('web'); // same result

"react-native": "0.61.2"
"react-native-fbsdk-next": "4.3.0",

**Comment by mikehardy** [comment]
Please try with current versions of react-native just in case
No idea why release vs debug scheme would make a difference here? Those sorts of problems are notoriously difficult to reproduce for maintainers (like me/us) because release mode in iOS and running on device requires Xcode development teams set up and a real app etc etc.

Stated more clearly: If you have a reproduction for this in a real app, you will probably be the only person that can drive a fix here. Reach into the javascript and the iOS code and add as much logging as you can (use patch-package to preserve your changes) and inspect every single parameter going into an API and every single API result to see if you can log out the full state of everything and find the problem that's what I'd do. Then post a PR and we can merge it...

In the absence of your effort I doubt anything will happen here though - too difficult to reproduce for other people

**Comment by messycoding** [comment]
I am not a master in object c so with my limited knowledge it would take time for me to figure out the issue so the quick solution I did was installed the react-native-fbsdk@3.0.0 back and it worked. For now I will stay in this version since I am in a tight schedule. But thank you so much for the response.
