### ISSUE TITLE
[Question] Deprecating Facebook Login support on Android WebViews

### ISSUE THREAD

**Issue by dazzyjong** [thebergamo/react-native-fbsdk-next#88]
I recently received an email that the facebook sdk will deprecates the android webview. Does this library prepare this issue?

**Comment by oolionoo** [comment]
I also received the email. But I don't know how to solve it.

Here is some info.
https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews

**Comment by mikehardy** [comment]
1. `Using SDK 8+`? :heavy_check_mark: 

https://github.com/thebergamo/react-native-fbsdk-next/blob/b550f106ccf66cbda4480c51a9ec81f58196806b/android/build.gradle#L47

2. `Ensure that you are NOT setting LoginBehavior=WEB_VIEW_ONLY. `

We are not?

3. `Ensure that your app has configured support for Custom Tabs properly. [....] You should see a window open in the external browser rather than in a native WebDialog.`

It does for me.

4. `If you have already completed steps 1–3 and have released your app to users, users who are on older versions of your application will see the following error message when they attempt to login from a webview, prompting them to upgrade to the newest version of your application.`

You must release a new version if you need to do 1-3 above.

5. `If your app is used primarily on devices which are unable to host the login experience in an external browser, we encourage you to integrate Device Login as an alternative login mechanism. `

Not in scope for this repository I think.

I do not believe there is anything actionable for this module here? Am I missing something?

**Comment by mikehardy** [comment]
I've been testing other things today and I was able to confirm all of my above points.
There is no action for us here, I don't think.
